services:
  - type: web
    name: expense-tracker-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: 'django-insecure-d5kyx)5gti+2&*be+h2)$@zw0a8+-ok7r&^!%!b^38gff5jwhd'
        generateValue: true



        