# Generated by Django 5.2.4 on 2025-08-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_expense_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
