# Generated by Django 5.2.4 on 2025-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='notify_on_threshold',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='yearly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
