# Generated by Django 5.2.4 on 2025-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_budget_notify_on_threshold_alter_budget_daily_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
